spring.application.name=chatapp

server.port=${PORT:8080}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/chatappdb}
spring.data.mongodb.auto-index-creation=true

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

spring.data.redis.url=${REDIS_URL:redis://localhost:6379}